# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e1684e2fb03a5240a9f7d11bd2929adcaba196fa3d13710ec759c522795bbd68e88d37187ab21795fbeec677d6f5af89a6865d4a7c031acd11441734bc121d0

test:
  secret_key_base: 872e11dc25b8820b622ac00a22d443985d758c4512e2a909ef217a6cde6a07aee3ba97ebea56de25a89bd5385525d018f7bbf6a7bcb2124688460106e54ca9b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
